---
- name: Configuro servidor base de datos en ubuntu
  hosts: srv1ubuntu
  become: true
  user: sysadmin

  tasks:
    - name: UFW instalado
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Permitir puerto 22 en ufw
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: Defino políticas de tráfico saliente
      community.general.ufw:
        policy: allow
        direction: outgoing
        state: enabled

    - name: Defino políticas de tráfico entrante
      community.general.ufw:
        policy: deny
        direction: incoming
        state: enabled

    - name: Servicio UFW levantado y activo
      ansible.builtin.systemd:
        name: ufw
        state: started
        enabled: true

    ## Instalación de base de datos
    - name: MariaDB instalado
      ansible.builtin.apt:
        name: mariadb-server
        state: present
        update_cache: true

    - name: Cambiar la configuración para escuchar en todas las interfaces
      ansible.builtin.lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address         = 0.0.0.0'
      notify: Restart mariadb

    - name: Servidor MariaDB levantado
      ansible.builtin.systemd: 
        name: mariadb
        state: started
        enabled: true

    - name: Habilitamos en ufw la conexión a MariaDB
      community.general.ufw:
        rule: allow
        port: '3306'
        protocol: tcp
        direction: in

    ## Configuración de la base de datos
    - name: Creo la base de datos todo
      community.mysql.mysql_db:
        check_implicit_admin: true
        login_host: "{{ hostvars[inventory_hostname].ansible_host }}"
        login_user: prueba
        login_password: prueba2024
        name: todo
        state: import
        target: ./files/todo.sql
      delegate_to: localhost
      connection: local

  handlers:
    - name: Restart mariadb
      ansible.builtin.systemd: 
        name: mariadb
        state: restarted

