---
- name: Install Java 11 OpenJDK and clean dnf cache
  hosts: srv2centos
  become: yes

  tasks:
    
    - name: Instalar tar
      ansible.builtin.dnf:
        url: "{{ tomcat_url }}"
        dest: /opt
      register: tomcat_file          
